//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/poject_1.png 的本地化字符串。
        /// </summary>
        internal static string Computer_img {
            get {
                return ResourceManager.GetString("Computer_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 智游链发挥区块链的技术优势，依托景点等旅游资源，在游客、商家、运营商之间建立一个信任链，打造“区块链+旅游”商业应用开放平台，实现旅游资产的价值数字化，完善旅游商业服务生态链。
        ///通过链接企业、游客、用户、运营商为全球旅游企业和游客搭建去中心化的互联网应用。
        ///•旅游公司
        ///•景点
        ///•游客
        ///•应用平台 的本地化字符串。
        /// </summary>
        internal static string Content_detail1 {
            get {
                return ResourceManager.GetString("Content_detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类似游戏平台的开发，使场景实景化，旅游景点的体验不再受到时间和空间的限制。体验更加丰富，增加了ITR的流动性。景点和酒店的预订方式也将因此改变，游客与玩家相互沟通交流转化，增强客户粘性，提升景区效益。 的本地化字符串。
        /// </summary>
        internal static string Content_detail2 {
            get {
                return ResourceManager.GetString("Content_detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Content_img1 {
            get {
                return ResourceManager.GetString("Content_img1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Content_img2 {
            get {
                return ResourceManager.GetString("Content_img2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Content_img3 {
            get {
                return ResourceManager.GetString("Content_img3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Globe_bg_img {
            get {
                return ResourceManager.GetString("Globe_bg_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从此每个项目不在独立，游客与玩家紧密的联系在一起 旅游不在受到时间和空间的限制，体验不在受到时间和 空间的限制，体验更加的丰富和多样。 的本地化字符串。
        /// </summary>
        internal static string Globe_detail {
            get {
                return ResourceManager.GetString("Globe_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 世界旅游的格局从此改变 的本地化字符串。
        /// </summary>
        internal static string Globe_title {
            get {
                return ResourceManager.GetString("Globe_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Home_bg_img {
            get {
                return ResourceManager.GetString("Home_bg_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打造全球领先的旅游互联网4.0区块链应用开放平台 的本地化字符串。
        /// </summary>
        internal static string Home_Detail {
            get {
                return ResourceManager.GetString("Home_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 智游链 - 旅游遇上智能合约 的本地化字符串。
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /zh 的本地化字符串。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Lang_Chinese {
            get {
                return ResourceManager.GetString("Lang_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 区块链浏览器 的本地化字符串。
        /// </summary>
        internal static string Menu_Browser {
            get {
                return ResourceManager.GetString("Menu_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系我们 的本地化字符串。
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下载 的本地化字符串。
        /// </summary>
        internal static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公告 的本地化字符串。
        /// </summary>
        internal static string Menu_Notice {
            get {
                return ResourceManager.GetString("Menu_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 虚位以待 的本地化字符串。
        /// </summary>
        internal static string Partner_1 {
            get {
                return ResourceManager.GetString("Partner_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Partner_2 {
            get {
                return ResourceManager.GetString("Partner_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Partner_3 {
            get {
                return ResourceManager.GetString("Partner_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Partner_4 {
            get {
                return ResourceManager.GetString("Partner_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Partner_5 {
            get {
                return ResourceManager.GetString("Partner_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Partner_6 {
            get {
                return ResourceManager.GetString("Partner_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作伙伴选择 的本地化字符串。
        /// </summary>
        internal static string Partner_title {
            get {
                return ResourceManager.GetString("Partner_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 智游链是一个旅游协议，而且是一个去中心化的自动执行系统，通过自由链交易，让用户降低风险，降低交易成本。通过应用的接入提升旅游项目价值，丰富旅游项目的体验方式，增强客户粘性。随着流动性的不断增加，我们将构建一个未来基于旅游业的金融体系 ，和区块链应用平台。 的本地化字符串。
        /// </summary>
        internal static string Project_sub_detail {
            get {
                return ResourceManager.GetString("Project_sub_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用于旅游业的企业区块链解决方案 的本地化字符串。
        /// </summary>
        internal static string Project_sub_title {
            get {
                return ResourceManager.GetString("Project_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 iTChain介绍 的本地化字符串。
        /// </summary>
        internal static string Project_Title {
            get {
                return ResourceManager.GetString("Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 点对点分布式信息传输、存储，为用户提供一个可以完全自由可依赖的数据发布，存储，传播平台。 的本地化字符串。
        /// </summary>
        internal static string Timeline_sub1 {
            get {
                return ResourceManager.GetString("Timeline_sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 线上应用平台开发，线下实体对接。 的本地化字符串。
        /// </summary>
        internal static string Timeline_sub2 {
            get {
                return ResourceManager.GetString("Timeline_sub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 应用场景丰富，线上社区形成。 的本地化字符串。
        /// </summary>
        internal static string Timeline_sub3 {
            get {
                return ResourceManager.GetString("Timeline_sub3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 伟大启航 的本地化字符串。
        /// </summary>
        internal static string Timeline_sub4 {
            get {
                return ResourceManager.GetString("Timeline_sub4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 平台发展路线图 的本地化字符串。
        /// </summary>
        internal static string Timeline_title {
            get {
                return ResourceManager.GetString("Timeline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/logo.png 的本地化字符串。
        /// </summary>
        internal static string Web_Logo {
            get {
                return ResourceManager.GetString("Web_Logo", resourceCulture);
            }
        }
    }
}
