//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/fzgh_pic.png 的本地化字符串。
        /// </summary>
        internal static string Develop_Icon {
            get {
                return ResourceManager.GetString("Develop_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/fzgh_img.png 的本地化字符串。
        /// </summary>
        internal static string Develop_IconFoot {
            get {
                return ResourceManager.GetString("Develop_IconFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/num_1.png 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_icon1 {
            get {
                return ResourceManager.GetString("Develop_sub_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/num_2.png 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_icon2 {
            get {
                return ResourceManager.GetString("Develop_sub_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/num_3.png 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_icon3 {
            get {
                return ResourceManager.GetString("Develop_sub_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/num_4.png 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_icon4 {
            get {
                return ResourceManager.GetString("Develop_sub_icon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/num_5.png 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_icon5 {
            get {
                return ResourceManager.GetString("Develop_sub_icon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2017 年1月 - 6 月 可行性调研 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_title1 {
            get {
                return ResourceManager.GetString("Develop_sub_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2017 年7月 - 12 月 区块链底层的搭建 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_title2 {
            get {
                return ResourceManager.GetString("Develop_sub_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2018 年1月 - 2 月 发行 NWToken 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_title3 {
            get {
                return ResourceManager.GetString("Develop_sub_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2018 年7月前 完成应用层商城搭建 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_title4 {
            get {
                return ResourceManager.GetString("Develop_sub_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2018 年 12月前 完成签约 1000 家商户上链的目标 的本地化字符串。
        /// </summary>
        internal static string Develop_sub_title5 {
            get {
                return ResourceManager.GetString("Develop_sub_title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发展规划 的本地化字符串。
        /// </summary>
        internal static string Develop_Title {
            get {
                return ResourceManager.GetString("Develop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 REGISTER OF TOKEN 的本地化字符串。
        /// </summary>
        internal static string Home_btnRegister {
            get {
                return ResourceManager.GetString("Home_btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 WHITEPAPER 的本地化字符串。
        /// </summary>
        internal static string Home_btnWhitePaper {
            get {
                return ResourceManager.GetString("Home_btnWhitePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 NedToken是将权利从中心化的电商平台或者大广告商中释放出来的关键，基于NWT的流通机制，让市场自由回归中小商家和消费者，真正解决了垄断、隐私主权等问题，生态系统中活跃的各方参与者均能从中获得激励。 的本地化字符串。
        /// </summary>
        internal static string Home_Detail {
            get {
                return ResourceManager.GetString("Home_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新维链·重构电商数据生态链 的本地化字符串。
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Lang_Chinese {
            get {
                return ResourceManager.GetString("Lang_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Link_Facebook {
            get {
                return ResourceManager.GetString("Link_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Link_Telegram {
            get {
                return ResourceManager.GetString("Link_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Link_Twitter {
            get {
                return ResourceManager.GetString("Link_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Link_WeChat {
            get {
                return ResourceManager.GetString("Link_WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Link_Weibo {
            get {
                return ResourceManager.GetString("Link_Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作伙伴 的本地化字符串。
        /// </summary>
        internal static string Menu_Partner {
            get {
                return ResourceManager.GetString("Menu_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目介绍 的本地化字符串。
        /// </summary>
        internal static string Menu_Project {
            get {
                return ResourceManager.GetString("Menu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 团队 的本地化字符串。
        /// </summary>
        internal static string Menu_Team {
            get {
                return ResourceManager.GetString("Menu_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_01.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon1 {
            get {
                return ResourceManager.GetString("Partner_sub_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_02.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon2 {
            get {
                return ResourceManager.GetString("Partner_sub_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_03.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon3 {
            get {
                return ResourceManager.GetString("Partner_sub_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_04.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon4 {
            get {
                return ResourceManager.GetString("Partner_sub_icon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_05.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon5 {
            get {
                return ResourceManager.GetString("Partner_sub_icon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/hzlogo_06.png 的本地化字符串。
        /// </summary>
        internal static string Partner_sub_icon6 {
            get {
                return ResourceManager.GetString("Partner_sub_icon6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作伙伴 的本地化字符串。
        /// </summary>
        internal static string Partner_Title {
            get {
                return ResourceManager.GetString("Partner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &lt;p style=&quot;margin-top: 5px; text-indent: 2em;&quot;&gt;
        ///    NedToken是全球首家基于区块链技术的电商供应链数 据生态。以先进的数据加密、区块链智能合约技术帮助商 家、消费者获得消费数据的所有权，控制权和收益权，实现 商家，消费者和品牌商的共臝合作。
        ///&lt;/p&gt;
        ///&lt;p style=&quot;text-indent: 2em;&quot;&gt;
        ///    NedToken就是要重构电商供应链数据生态。&amp;nbsp;
        ///&lt;/p&gt;
        ///&lt;p style=&quot;text-indent: 2em;&quot;&gt;
        ///    NedToken(新维链）的使命，简单的说，就是让数据自 由、安全、便捷的流通，消灭库存，让数字营销变得简单。
        ///&lt;/p&gt;
        ///&lt;p style=&quot;text-indent: 2em;&quot;&gt;
        ///    NedToken将通过分布式、去中心化的区块链底层平 台，让数据的所有权归属用户（商家和消费者），并在用户 充分授权的情况下，通过自由、安全、便捷的流通，产生回 报和收益。
        ///&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string Project_Detail {
            get {
                return ResourceManager.GetString("Project_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 唯一不可篡改的表征价值 的本地化字符串。
        /// </summary>
        internal static string Project_sub_detail1 {
            get {
                return ResourceManager.GetString("Project_sub_detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 跨平台、跨系统价值流通 的本地化字符串。
        /// </summary>
        internal static string Project_sub_detail2 {
            get {
                return ResourceManager.GetString("Project_sub_detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 产品价值化，产品服务化 的本地化字符串。
        /// </summary>
        internal static string Project_sub_detail3 {
            get {
                return ResourceManager.GetString("Project_sub_detail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/jzbz_icon.png 的本地化字符串。
        /// </summary>
        internal static string Project_sub_icon1 {
            get {
                return ResourceManager.GetString("Project_sub_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/jzfw_icon.png 的本地化字符串。
        /// </summary>
        internal static string Project_sub_icon2 {
            get {
                return ResourceManager.GetString("Project_sub_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/jzlt_icon.png 的本地化字符串。
        /// </summary>
        internal static string Project_sub_icon3 {
            get {
                return ResourceManager.GetString("Project_sub_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 价值表征 的本地化字符串。
        /// </summary>
        internal static string Project_sub_title1 {
            get {
                return ResourceManager.GetString("Project_sub_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 价值流通 的本地化字符串。
        /// </summary>
        internal static string Project_sub_title2 {
            get {
                return ResourceManager.GetString("Project_sub_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 价值服务 的本地化字符串。
        /// </summary>
        internal static string Project_sub_title3 {
            get {
                return ResourceManager.GetString("Project_sub_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 NedToken项目介绍 的本地化字符串。
        /// </summary>
        internal static string Project_Title {
            get {
                return ResourceManager.GetString("Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 CONFIRM 的本地化字符串。
        /// </summary>
        internal static string Register_btnConfirm {
            get {
                return ResourceManager.GetString("Register_btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Thank you for the interest! Prior to participating in this LAB token sale, please ensure that you have read, understand and hereby accept the &lt;a class=&apos;Website&apos;&gt;Website Terms and Conditions&lt;/a&gt; and &lt;a class=&apos;Privacy&apos;&gt;Privacy Policy&lt;/a&gt; documents. Please fill in the form below to express your interest in our LAB token sale. 的本地化字符串。
        /// </summary>
        internal static string Register_Description {
            get {
                return ResourceManager.GetString("Register_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮箱* (EMAIL ADD) 的本地化字符串。
        /// </summary>
        internal static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请确认邮箱* (EMAIL ADD CONFIRM) 的本地化字符串。
        /// </summary>
        internal static string Register_EmailConfirm {
            get {
                return ResourceManager.GetString("Register_EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我已经阅读、理解并接受网站的相关协议、条件以及隐私声明等相关文件。 的本地化字符串。
        /// </summary>
        internal static string Register_Info1 {
            get {
                return ResourceManager.GetString("Register_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我在此确认，我不是中华人民共和国公民、新加坡公民、不是美国领土或辖地、美国的任何州和/或哥伦比亚特E的公民，也不是根据和/或中国、新加坡、美国的法律成立 和/或管辖的公司、合伙或其他法律实体（包括但不限于分支机构或办公室或代表处），并不被禁止参与购买或持有Token。 的本地化字符串。
        /// </summary>
        internal static string Register_Info2 {
            get {
                return ResourceManager.GetString("Register_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我在此确认，我有足够的法定年龄（至少18岁，或已经符合我所在的国藉国法律规定的完全民事行为能力人），我有独立的意思表示能力作出判断也有足够的能力购买Token。 的本地化字符串。
        /// </summary>
        internal static string Register_Info3 {
            get {
                return ResourceManager.GetString("Register_Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名* (NAME) 的本地化字符串。
        /// </summary>
        internal static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话* (TELEPHONE) 的本地化字符串。
        /// </summary>
        internal static string Register_Phone {
            get {
                return ResourceManager.GetString("Register_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 代币注册 / REGISTER FOR TOKEN 的本地化字符串。
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 以太币钱包地址（ ETH WALLET ADDRESS) 的本地化字符串。
        /// </summary>
        internal static string Register_WalletAddress {
            get {
                return ResourceManager.GetString("Register_WalletAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon1 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon2 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon3 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon4 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon5 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon6 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_icon7 {
            get {
                return ResourceManager.GetString("TeamCore_sub_icon7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Todd Chaffee IVP基金合伙人 Coinbase投资人 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name1 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Paul Veradittakit Pantera Capital合伙人 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name2 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 武源文 井通科技执行董事 兼CEO 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name3 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 陈小虎 井通科技首席科学家 MOAC项目技术负责人 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name4 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Timo Hanke DIFNITY基金会工程总监 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name5 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Nader Al-Naji Basecoin Founder/CEO 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name6 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Linda Xie Scalar Capital联合创始人 的本地化字符串。
        /// </summary>
        internal static string TeamCore_sub_name7 {
            get {
                return ResourceManager.GetString("TeamCore_sub_name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 投资人及核心顾问 的本地化字符串。
        /// </summary>
        internal static string TeamCore_Title {
            get {
                return ResourceManager.GetString("TeamCore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 NEDT 项目负责人、基金会秘书长；毕业于新加坡南洋理工大学计算机专业，15年世界500强IT高管经验，区块链信徒。曾任惠普亚太区CTO/COO。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail1 {
            get {
                return ResourceManager.GetString("Team_sub_detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 前互联网金融公司资易通CTO，前小米投资生态链创业公司小寻科技云服务部技术总监（2017中国最具投资价值公司Top 50)，前中兴通信云计算、大数据架构师、幵发经理。拥有近20年产品、研发、运维经验，在小寻公司期间负责物联网及数据处理平台开发及运维工作，期间研究区块链在物联网上的应用。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail2 {
            get {
                return ResourceManager.GetString("Team_sub_detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 精通Angular、React、NodeJs等多种前端开发语言及可视化工具，在网络安全，P2P文件分发网络、网络爬虫等方向具有丰富经验。区块链热爱者，精通区块链原理及智能合约技术，致力于打造国内顶尖区块链项目。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail3 {
            get {
                return ResourceManager.GetString("Team_sub_detail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数字货币早期投资人、巴比特专栏金牌作家，多家投资机构战略合作顾问，其对数字货币一级市场有着深刻的认知，是区块链骨灰级研究者，除持仓主流货币外，是Ardor, IOTA, IPFS, EOS, MANA等项目的早期参与者，均获得了巨大收益，目前指导多家区块链团队的项目运营。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail4 {
            get {
                return ResourceManager.GetString("Team_sub_detail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 资深视觉设计师，曾主导过多项互联网金融产品设计及金融品牌设计。具有丰富的互联网产品设计与品牌设计经验，倡导遵从用户诉求，满足用户体验需求的设计理念，致力于提升互联网金融数据产品的设计体验。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail5 {
            get {
                return ResourceManager.GetString("Team_sub_detail5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 毕业于北京大学经济学硕士，曾任保洁（中国）高级市场总监，泛华集团信息战略系统负责人，擅长品牌打造和粉丝社群营销。数字货币早期研究者，曾负责热门项目分析、运营工作，对金融产品生态和投资哲学有深刻的见解。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail6 {
            get {
                return ResourceManager.GetString("Team_sub_detail6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首席法律顾问，美国华尔街知名律师。主要服务过：滚石唱片、米高梅、迪士尼、Wework等。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail7 {
            get {
                return ResourceManager.GetString("Team_sub_detail7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 美国密歇根大学密码学博士，精通网络协议、加密算法、DDos攻击防护。对区块链中的信任关系，交易一致性，交易有无欺诈，信息是否被篡改，数据存储的可靠性以及隐私保护，有深虔研究。在国际信息安全与密码学的会议和杂志上发表论文近30篇， 拥有多项信息安全方向专利。 的本地化字符串。
        /// </summary>
        internal static string Team_sub_detail8 {
            get {
                return ResourceManager.GetString("Team_sub_detail8", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon1 {
            get {
                return ResourceManager.GetString("Team_sub_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon2 {
            get {
                return ResourceManager.GetString("Team_sub_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon3 {
            get {
                return ResourceManager.GetString("Team_sub_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon4 {
            get {
                return ResourceManager.GetString("Team_sub_icon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon5 {
            get {
                return ResourceManager.GetString("Team_sub_icon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon6 {
            get {
                return ResourceManager.GetString("Team_sub_icon6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon7 {
            get {
                return ResourceManager.GetString("Team_sub_icon7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Team_sub_icon8 {
            get {
                return ResourceManager.GetString("Team_sub_icon8", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SKY YU 首席执行官 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name1 {
            get {
                return ResourceManager.GetString("Team_sub_name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 粟泰云 首席技术官 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name2 {
            get {
                return ResourceManager.GetString("Team_sub_name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 杨波 项目技术总监 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name3 {
            get {
                return ResourceManager.GetString("Team_sub_name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 程君 首席分祈师 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name4 {
            get {
                return ResourceManager.GetString("Team_sub_name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Bruce Yu 设计总监 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name5 {
            get {
                return ResourceManager.GetString("Team_sub_name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Tim Guan 市场总监 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name6 {
            get {
                return ResourceManager.GetString("Team_sub_name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Scott Beber 首席法律顾问 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name7 {
            get {
                return ResourceManager.GetString("Team_sub_name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Alfred Chen密码学专家 的本地化字符串。
        /// </summary>
        internal static string Team_sub_name8 {
            get {
                return ResourceManager.GetString("Team_sub_name8", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目核心团队 的本地化字符串。
        /// </summary>
        internal static string Team_Title {
            get {
                return ResourceManager.GetString("Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 /Public/images/logo_icon.png 的本地化字符串。
        /// </summary>
        internal static string Web_Logo {
            get {
                return ResourceManager.GetString("Web_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新维链 的本地化字符串。
        /// </summary>
        internal static string Web_Name {
            get {
                return ResourceManager.GetString("Web_Name", resourceCulture);
            }
        }
    }
}
